// Generated by ts-to-zod
import { z } from "zod";

export const departmentSchema = z.object({
  id: z.number(),
  name: z.string(),
});

export const clientSchema = z.object({
  id: z.number(),
  called: z.boolean(),
  departmentId: z.number(),
  updatedAt: z.date(),
});

export const deskSchema = z.object({
  id: z.number(),
  number: z.number(),
  clientId: z.number().nullable(),
  client: clientSchema.nullable(),
});
