/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DisplayImport } from './routes/display'
import { Route as InitialImport } from './routes/_initial'
import { Route as AppImport } from './routes/_app'
import { Route as InitialLogInImport } from './routes/_initial/logIn'
import { Route as InitialChooseDeskImport } from './routes/_initial/chooseDesk'
import { Route as AppSettingsImport } from './routes/_app/settings'
import { Route as AppDashboardImport } from './routes/_app/dashboard'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DisplayRoute = DisplayImport.update({
  path: '/display',
  getParentRoute: () => rootRoute,
} as any)

const InitialRoute = InitialImport.update({
  id: '/_initial',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const InitialLogInRoute = InitialLogInImport.update({
  path: '/logIn',
  getParentRoute: () => InitialRoute,
} as any)

const InitialChooseDeskRoute = InitialChooseDeskImport.update({
  path: '/chooseDesk',
  getParentRoute: () => InitialRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_initial': {
      preLoaderRoute: typeof InitialImport
      parentRoute: typeof rootRoute
    }
    '/display': {
      preLoaderRoute: typeof DisplayImport
      parentRoute: typeof rootRoute
    }
    '/_app/dashboard': {
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/settings': {
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/_initial/chooseDesk': {
      preLoaderRoute: typeof InitialChooseDeskImport
      parentRoute: typeof InitialImport
    }
    '/_initial/logIn': {
      preLoaderRoute: typeof InitialLogInImport
      parentRoute: typeof InitialImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AppRoute.addChildren([AppDashboardRoute, AppSettingsRoute]),
  InitialRoute.addChildren([InitialChooseDeskRoute, InitialLogInRoute]),
  DisplayRoute,
])

/* prettier-ignore-end */
