/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DisplayImport } from './routes/display'
import { Route as InitialImport } from './routes/_initial'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as InitialLogInImport } from './routes/_initial/logIn'
import { Route as InitialChooseDeskImport } from './routes/_initial/chooseDesk'
import { Route as AuthKioskImport } from './routes/_auth/kiosk'
import { Route as AuthAppImport } from './routes/_auth/_app'
import { Route as AuthAppSettingsImport } from './routes/_auth/_app/settings'
import { Route as AuthAppDashboardImport } from './routes/_auth/_app/dashboard'

// Create/Update Routes

const DisplayRoute = DisplayImport.update({
  path: '/display',
  getParentRoute: () => rootRoute,
} as any)

const InitialRoute = InitialImport.update({
  id: '/_initial',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InitialLogInRoute = InitialLogInImport.update({
  path: '/logIn',
  getParentRoute: () => InitialRoute,
} as any)

const InitialChooseDeskRoute = InitialChooseDeskImport.update({
  path: '/chooseDesk',
  getParentRoute: () => InitialRoute,
} as any)

const AuthKioskRoute = AuthKioskImport.update({
  path: '/kiosk',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppRoute = AuthAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppSettingsRoute = AuthAppSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AuthAppRoute,
} as any)

const AuthAppDashboardRoute = AuthAppDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthAppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_initial': {
      preLoaderRoute: typeof InitialImport
      parentRoute: typeof rootRoute
    }
    '/display': {
      preLoaderRoute: typeof DisplayImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_app': {
      preLoaderRoute: typeof AuthAppImport
      parentRoute: typeof AuthImport
    }
    '/_auth/kiosk': {
      preLoaderRoute: typeof AuthKioskImport
      parentRoute: typeof AuthImport
    }
    '/_initial/chooseDesk': {
      preLoaderRoute: typeof InitialChooseDeskImport
      parentRoute: typeof InitialImport
    }
    '/_initial/logIn': {
      preLoaderRoute: typeof InitialLogInImport
      parentRoute: typeof InitialImport
    }
    '/_auth/_app/dashboard': {
      preLoaderRoute: typeof AuthAppDashboardImport
      parentRoute: typeof AuthAppImport
    }
    '/_auth/_app/settings': {
      preLoaderRoute: typeof AuthAppSettingsImport
      parentRoute: typeof AuthAppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthAppRoute.addChildren([AuthAppDashboardRoute, AuthAppSettingsRoute]),
    AuthKioskRoute,
  ]),
  InitialRoute.addChildren([InitialChooseDeskRoute, InitialLogInRoute]),
  DisplayRoute,
])

/* prettier-ignore-end */
