version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=nala
      - POSTGRES_PASSWORD=ladelpollodorado
    volumes:
      - qmsDatabase:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  qmsDatabase:
